phases:
- phase: Linux
  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget
    NUGET_HTTP_CACHE_PATH: $(Agent.WorkFolder)\.nuget-http-cache

  steps:
  - checkout: self
    clean: true

  - bash: |
      cd $(Agent.WorkFolder)
      git clone https://github.com/juj/emsdk.git
      cd emsdk
      ./emsdk install latest
      ./emsdk activate latest
    displayName: 'Run make'

  - bash: |
      source $(Agent.WorkFolder)/emsdk/emsdk_env.sh
      npm -g install typescript
      npm install
      make
      mono src/nuget/nuget.exe pack src/nuget/uno.sqlite-wasm.nuspec -Version "1.0.0-dev.$(Build.BuildId)" -OutputDirectory "$(build.artifactstagingdirectory)"
    displayName: 'Run make'

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(build.sourcesdirectory)/dist
      Contents: '*.*'
      TargetFolder: $(build.artifactstagingdirectory)/dist
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    # https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: drop
      ArtifactType: Container